### ISSUE TITLE
Flatpak

### ISSUE THREAD

**Issue by JakobDev** [Rangi42/polished-map#71]
I've created created a Flatpak for polished-map. Flatpak is a universal container based package system for Linux. If you create a Flatpak, polished-map can be installed on every Linux Distro without any problems. You can also publish to [Flathub](https://flathub.org/), which is a universal AppStore for Linux. This would mean a one click install on almost every Linux Distro.

Here is the Manifest:
```yaml
app-id: io.github.Rangi42.polished-map
runtime: org.freedesktop.Platform
runtime-version: "22.08"
sdk: org.freedesktop.Sdk
command: polishedmap
finish-args:
  - --filesystem=host:rw
  - --socket=fallback-x11
  - --socket=wayland
  - --device=dri
  - --share=ipc

modules:
  - name: fltk
    buildsystem: autotools
    config-opts:
      - --with-abiversion=10307
    sources:
      - type: git
        url: https://github.com/fltk/fltk.git
        tag: release-1.3.7
        commit: 70ebfdb6a120533130ed4a25f83bd7ae2a501581
    cleanup:
      - /share

  - name: polished-map
    buildsystem: simple
    build-commands:
      - make
      - make install PREFIX=$FLATPAK_DEST
    sources:
      - type: archive
        archive-type: tar-gzip
        url: https://api.github.com/repos/Rangi42/polished-map/tarball/v4.7.1
        sha256: d4369600f9d98f1d63ca5a425ee30ff87c0b61212f8801647995670e3b6af3dc
        x-checker-data:
            type: json
            url: https://api.github.com/repos/Rangi42/polished-map/releases/latest
            version-query: .tag_name
            url-query: .tarball_url
            is-main-source: true
```
Save it as `io.github.Rangi42.polished-map.yaml`

Install all dependencies:
```
flatpak install org.freedesktop.Platform//22.08 org.freedesktop.Sdk//22.08 org.flatpak.Builder
```

Build and install:
```
flatpak run org.flatpak.Builder build-dir io.github.Rangi42.polished-map.yaml --force-clean --ccache --install --user
```

Run:
```
flatpak run io.github.Rangi42.polished-map
```

The Metadada (.desktop and Icon) needs to be made ready for Flatpak to be used, but everything else works. Tell me, if you are interested.
